### ISSUE TITLE
Unity project directory in subdirectory of git repository is not supported

### ISSUE THREAD

**Issue by WildRikku** [NibbleByte/UnityWiseGit#1]
[Title changed to reflect discussion below - was: No file ever locked]

Hello,

I am trying to use this asset mainly for the locks but no locks are ever requested. I traced it down until I figured that at this point https://github.com/NibbleByte/UnityWiseGit/blob/master/Assets/DevLocker/VersionControl/WiseGit/Editor/LockPrompting/GitLockPromptDatabase.cs#L337, `statusDatabaseData` contains 0 entries. I can perform other git operations with the plugin so I think nothing is globally broken or setup wrongly. Lock requests are enabled in the settings. I'd appreciate some help.

**Comment by NibbleByte** [comment]
The locks prompt uses the statuses retrieved by the `GitStatusesDatabase`. If it doesn't retrieve anything, it won't know what to lock. In order for this to happen, you need to enable overlay icons in the WiseGit preference window. Also make sure remote changes are fetched, and the refresh interval is a sensible number (in seconds).
![image](https://github.com/user-attachments/assets/b974c79e-d102-44c0-8136-bef0cb7dfa9d)

If fetching remote changes is set to "Same As Project Preference", then check in the "Project" tab.
![image](https://github.com/user-attachments/assets/b765e4d2-cac6-41c9-81f8-11fe9893d1fe)

Note: when fetching remote changes is enabled, this means WiseGit will regularly call "git fetch" in the background, downloading any remote changes to your local ".git" folder (this won't affect your working copy). If there are a lot of remote changes (added assets) it may take some time to download. Check if everything was fetched correctly.

Hint: use the context menu `Git / Refresh Icons & Locks` to manually refresh the icons. At the bottom right corner of the Unity window, you'll see the progress bar "Git Refresh" indicating that is working. Check if it manages to finish or it remains stuck forever.

As a last resort, can you type in cmd from your root folder the command `git status --porcelain` and post the output here.

**Comment by WildRikku** [comment]
Hi, sorry for coming back to this late and thanks for your response.

The problem was indeed that I did not have the overlay icons activated because I didn't need them. Now auto locks are attempted but result in an error:

```GitLockPromptDatabase Operations:
/usr/bin/git lfs lock "Assets/Scenes/ShopScene.unity"
Locking Assets/Scenes/ShopScene.unity failed: exit status 255

UnityEngine.Debug:LogError (object)
DevLocker.VersionControl.WiseGit.WiseGitIntegration/ResultConsoleReporter:Dispose () (at Assets/DevLocker/VersionControl/WiseGit/Editor/WiseGitIntegration.cs:266)
DevLocker.VersionControl.WiseGit.LockPrompting.GitLockPromptDatabase/<>c__DisplayClass17_0:<LockEntries>b__1 (DevLocker.VersionControl.WiseGit.GitAsyncOperation`1<DevLocker.VersionControl.WiseGit.LockOperationResult>) (at Assets/DevLocker/VersionControl/WiseGit/Editor/LockPrompting/GitLockPromptDatabase.cs:312)
DevLocker.VersionControl.WiseGit.GitAsyncOperation`1<DevLocker.VersionControl.WiseGit.LockOperationResult>:Update () (at Assets/DevLocker/VersionControl/WiseGit/Editor/GitAsyncOperation.cs:127)
UnityEditor.EditorApplication:Internal_CallUpdateFunctions () (at /home/bokken/build/output/unity/unity/Editor/Mono/EditorApplication.cs:381)
```

However, running `/usr/bin/git lfs lock "Assets/Scenes/ShopScene.unity"` in a terminal does not result in a code 255, it results in a code 0.

The project explorer marks changed files with a red circle with a white exclamation mark. Running "get locks" on one of them doesn't seem to do anything, not even on the file that I locked from the terminal.

**Comment by NibbleByte** [comment]
This looks like an error within git lfs itself. I'll need more information about your setup.
What operating system and git version are you using? For git type in `git version` and `git lfs version`. How are they installed (by the OS, homebrew, MacPorts), where is the git binary and where is the lfs binary?

Did you specify binary path (i.e. "Git CLI Path") in the preferences? Can you try leaving it empty?

If you're using MacOS (or Linux?), note that the Terminal is using more environment variables than Unity started from the UnityHub. In other words, the Terminal PATH variable contains `/usr/local/bin` while running Unity **does not**. This may be the reason you see different results in the Terminal.
In the WiseGit plugin I have accounted for this and included the default binaries paths, but I may have missed the ones from your installation.

> Running "get locks" on one of them doesn't seem to do anything, not even on the file that I locked from the terminal.

This is because context menus of WiseGit just forward your request to other software with better GUI. For Windows that would be TortoiseGit, for OSX that is SnailGit, for Linux is RabbitVCS. If nothing pops up, you probably don't have any of those installed. The only viable option is to go to the preferences and switch the "Context menus client" to "CLI" which is a poor man's terminal in Unity window - a crude fallback.

![image](https://github.com/user-attachments/assets/ad03fc83-6bfd-463b-89bb-fafbaab9b19c)

**Comment by WildRikku** [comment]
git version is 2.46.1, LFS version is `git-lfs/3.5.1 (GitHub; linux amd64; go 1.22.1)`. This is on Manjaro Linux so they were installed using pacman. Both git and git-lfs executables reside in `/usr/bin`. 

Git CLI Path was `/usr/bin/git`. Leaving it empty changed nothing.

Regarding the context menu, I set the client to CLI (which is sufficient for me), which resulted in a CLI popping up in Unity as you described which showed a "Failed" at the bottom for the "Get locks" context menu action - as expected, as auto-locking also does not work.

If it helps, I can send you the test project I used to reproduce the issue. It is rather crude because I copied together some files from other projects to have something to mess with, it's not a functioning Unity project, but I guess that's not relevant as I only care about the files.

**Comment by NibbleByte** [comment]
No need for a project. I've tested WiseGit under Ubuntu and it seemed to work. But your distro seems to have different setup. I'm 80% that this is the same issue as on OSX. Can you try enabling the "fix" for OSX to compile for Linux as well?
Go to `GitPreferencesManager.cs` file, scroll down to the `CheckGitSupport()` on line 333. The first line of the function is a #if preprocessor for OSX. Please change it from
`#if UNITY_EDITOR_OSX`
to
`#if UNITY_EDITOR_OSX || UNITY_EDITOR_LINUX`

![image](https://github.com/user-attachments/assets/94ceff5e-ee96-4863-a2b2-b69139feb3e1)

Also make sure that the **"Git CLI Path" remains empty**.
**Restart Unity after that to take effect.**

This will make sure that default binary paths are included in the PATH environment variable (only for the running Unity), so shell commands can find git & lfs executables.

**Comment by WildRikku** [comment]
> Please change it from
> #if UNITY_EDITOR_OSX
> to
> #if UNITY_EDITOR_OSX || UNITY_EDITOR_LINUX

That did not have any effect. The code there however does not add my binary folder, which is `/usr/bin`. I added another if block to add `/usr/bin`, too, but that also did not help.

However, I noticed that when I now add my CLI path to the settings and try to save it, the dialogue complains that it could not find the executable in that folder, even though it's clearly there and the path was accepted before.

**Comment by NibbleByte** [comment]
Ah yes, `/usr/bin` wasn't on the list, as it wasn't needed on OSX.  When you added it, did you restart Unity? As recompile won't refresh it (I'm doing some neat tricks to avoid initializing every time on recompile).

Don't add Git CLI Path in the preferences, I'm quite sure it wouldn't work. I need to remove that preference. :(

**Comment by WildRikku** [comment]
> Ah yes, `/usr/bin` wasn't on the list, as it wasn't needed on OSX. When you added it, did you restart Unity? As recompile won't refresh it (I'm doing some neat tricks to avoid initializing every time on recompile).
> 
> Don't add Git CLI Path in the preferences, I'm quite sure it wouldn't work. I need to remove that preference. :(

Yes, I restarted the editor both times, when I removed the comment and then once again after I added the additional if block.

Why do you think setting the path in the preference would not work? I noticed that while it was there, it showed up in the log (like here https://github.com/NibbleByte/UnityWiseGit/issues/1#issuecomment-2484052441) but since I removed that, the log only shows `git` with no path, which is probably because you rely on the `PATH` variable.

**Comment by NibbleByte** [comment]
As far as I remember, setting CLI path to use, didn't work well with lfs and maybe some other functionality. It may run `/usr/bin/git` with absolute path, but git itself won't find the lfs executable.

The best fix is to make sure it runs naturally as it does in the Terminal. Can you echo your PATH variable in the Terminal? Maybe we're missing something. You may even try to copy the output and set it directly in the code with `Environment.SetEnvironmentVariable(...);`

**Comment by WildRikku** [comment]
My `PATH` is `/home/WildRikku/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl`. Nothing that I would expect to be relevant. I copied it to Unity anyway by setting it directly inside the "Mac OS workaround" code I extended before, but that did not help.

Googling what return code 255 means it seems to be related to connecting to the remote. We use SSH, is it possible Unity or your plugin have trouble establishing the SSH connection? Do you possibly run as a different user that would not have access to my SSH keys?

**Comment by WildRikku** [comment]
I figured it out. It was indeed an issue with my system configuration and SSH.

Git uses `ssh-add` to get and remember the ssh key. `ssh-add` uses `ssh-askpass` to get the password from the user via a convenient dialogue. I, however, use Manjaro KDE. KDE uses `ksshaskpass` instead and the Manjaro packagers forgot the recommended symlink, so `ssh-add` could not find `ssh-askpass`. I did not notice in my terminal because I use terminal-specific SSH helpers because I had trouble to get the terminal to remember the password.

I added it and now your plugin works as expected. The workaround you use for Mac OS is not required. Maybe I even fixed my terminal problems.

**Comment by WildRikku** [comment]
If I may ask for help again... it's alright if you don't want to bother. I was initially trying to figure out if your asset works with Unity 2021, too, when I stumbled upon the issue we talked about above. Everything works fine now in Unity 2022 and 2021, too - with fresh projects, that is. With my project I currently work on, assets still are not locked.

The thing is - I can lock them from the context menu. When I go to a terminal, they will show up. I do, however, not get a lock icon in the project manager, and lock prompts and auto-locking do not work.

I figured out that in this line https://github.com/NibbleByte/UnityWiseGit/blob/master/Assets/DevLocker/VersionControl/WiseGit/Editor/LockPrompting/GitLockPromptDatabase.cs#L345 `newEntries` is empty. I also figured out that `PostProcessAssets` is called correctly, so something has to happen in between that is somehow broken for my project. I'd appreciate support if you have time and thank you very much for your help so far.

**Comment by NibbleByte** [comment]
That is great. I'll add proper message if error 255 occurs, although I'm not sure what to say 😄 

About the other issue: do you have any overlay icons visible (modified, unversioned)? Note that modifying an asset may show icon briefly, but disappear in a few seconds after that (when the check actually happens).

The lock prompt is triggered when modified assets are detected. `GitLockPromptDatabase` asks the `GitStatusesDatabase` for it's knowledge for all the statuses (which is used for the icons). The `GitStatusesDatabase` runs regularly (on another thread) `git status --porcelain` at the root of the project, to gather this info for all the assets.
You can see this in the `WiseGitIntegration.GetStatuses()` method. Can you run this in the terminal, show me what you get?

If only lock icons are missing, the same function checks for locks as well: `git lfs locks --verify --json`. Can you check that one as well, at the project root?

**Comment by WildRikku** [comment]
I have "modified" icons that show up when I save a scene and disappear after a few seconds.

`git status --porcelain` shows something similar to:

``` 
M Unityfolder/Assets/Scenes/GameScene.unity
?? Unityfolder/notaddedfile.txt
?? irrelevantfile.txt
```

`git lfs locks --verify --json`

`{"ours":[],"theirs":[]}`

and after locking one asset via context menu (which then still does not show the lock icon):

```
{"ours":[{"id":"..","path":"Unityfolder/Assets/Prefabs/ModuleList.asset","owner":{"name":"WildRikku"},"locked_at":"2024-11-21T22:30:41Z"},{"id":"..","path":"Unityfolder/Assets/Prefabs/ModuleList.asset.meta","owner":{"name":"WildRikku"},"locked_at":"2024-11-21T22:30:41Z"}],"theirs":[]}```

**Comment by NibbleByte** [comment]
I think I know what is happening. Your Unity folder is not the root of the git repository, so the paths returned by git commands don't start with "Assets/...". I suspected this would be a problem, but didn't have time to test and fix.

I need to fix this properly everywhere, which would take time. Apologies for the inconvenience.

For hack-fix, you can do this:
Go to `WiseGitIntegration.cs` inside `ExtractStatuses()` replace the line
`statusData.Path = currentSubmoduleRoot + line.Substring(3);`
with
`statusData.Path = currentSubmoduleRoot + line.Replace("Unityfolder/", "").Substring(3);`

Go to `WiseGitIntegration.cs` inside `GetStatuses()` find this line
`locksJSONEntry.ExcludeOutsidePaths(path);`
and add this code after it
```
locksJSONEntry.ExcludeOutsidePaths(path);
for (int i = 0; i < locksJSONEntry.ours.Count; i++) {
	var our = locksJSONEntry.ours[i];
	our.path = path.Replace("Unityfolder/", "");
	locksJSONEntry.ours[i] = our;
}
for (int i = 0; i < locksJSONEntry.theirs.Count; i++) {
	var their = locksJSONEntry.theirs[i];
	their.path = path.Replace("Unityfolder/", "");
	locksJSONEntry.theirs[i] = their;
}
```
This is a partial fix and I'm not sure if it works, but you could try.

**Comment by WildRikku** [comment]
Thank you so much! It helped, I can now permanently see the "modified" icons and locks are registered and performed, but they are somehow performed twice, throwing an error the second time because the lock already exists, and yet there is no lock icon. It looks like this is also related to the base folder. I get:

```
GitLockPromptDatabase Operations:
git lfs lock "Assets/Scenes/GameScene.unity"
Locking Unityfolder/Assets/Scenes/GameScene.unity failed: Lock exists
```

and

```
Locking failed with result LockAlreadyExists for assets:
Assets/Scenes/GameScene.unity.
```

and right before that the success message:

```
Locked assets:
Assets/Scenes/GameScene.unity
```

Would it help to just put `Unityfolder/Assets` in the settings in target folder instead of just `Assets`?

**Comment by NibbleByte** [comment]
That is why I suspected my quick hack-fix won't work - all the code need to be reviewed and fixed. :( 

Not sure which settings you're referring to. But if git starts returning `Assets/...` paths, everything will work.

**Comment by WildRikku** [comment]
I looked into it again and got it to work. There was an error in the workaround here: https://github.com/NibbleByte/UnityWiseGit/issues/1#issuecomment-2493207329

`Replace` has to be called on `locksJSONEntry.ours[i].path`, not `path`.

Now locks are recognized correctly so I can use auto-locking, WiseGit will not try to lock again and the lock icon shows. :)

You are right that there are more places. I can see that it's tricky though. There is `Application.dataPath` which would give you the correct Unity folder to work on but it's only available on the main thread. There is also the option to give a working directory to the git commands but that does not help with LFS commands.

Anyway, thank you so much for your help, for now, I can live with the workaround, and if you ever got time to rework the code it will be much appreciated. I will rename this ticket accordingly. Feel free to ping me if you need someone to test something.

**Comment by WildRikku** [comment]
Oh, and for reference, here is my workaround for `WiseGitIntegration.GetStatuses()`:

```
		if (m_IsApplicationQuitting)
			return StatusOperationResult.UnknownError;

		locksJSONEntry = JsonUtility.FromJson<LocksJSONEntry>(result.Output);
				
                // hack begin
                for (int i = 0; i < locksJSONEntry.ours.Count; i++) {
                    var our = locksJSONEntry.ours[i];
                    our.path = locksJSONEntry.ours[i].path.Replace("Unityfolder/", "");
                    locksJSONEntry.ours[i] = our;
                }
                for (int i = 0; i < locksJSONEntry.theirs.Count; i++) {
                    var their = locksJSONEntry.theirs[i];
                    their.path = locksJSONEntry.theirs[i].path.Replace("Unityfolder/", "");
                    locksJSONEntry.theirs[i] = their;
                }
                // hack end
                
                locksJSONEntry.ExcludeOutsidePaths(path);
```

**Comment by NibbleByte** [comment]
I think I've fixed the code everywhere. You can download the fix from the #upm branch. Haven't released new version or published it anywhere yet, as I want to do some more fixes.

**Comment by WildRikku** [comment]
Hey great! As far as I can tell, it works. I removed the source files and used UPM and without any changes, auto-locking and status detection and icons worked. Thank you!
